const c = @import("c.zig").c;
const std = @import("std");

// =Colors=============================================================================================================

/// Helper for colors
pub const VibrantColor = enum(u8) {
    NeonBlaze,
    ElectricCrimson,
    HyperMagenta,
    NeonCoral,
    VoltageOrange,
    LuminousEmber,
    ElectricGold,
    NeonCitrus,
    RadioactiveLime,
    LaserGreen,
    GlowingEmerald,
    NeonAqua,
    ElectricCyan,
    NeonSky,
    HyperBlue,
    VividIndigo,
    ShockwaveViolet,
    ElectricAmethyst,
    NeonOrchid,
    FluorescentFuchsia,

    pub const palette = [_][4]f32{
        .{ 1.000, 0.039, 0.329, 1.0 }, // #FF0A54 - Neon Blaze
        .{ 1.000, 0.125, 0.306, 1.0 }, // #FF204E - Electric Crimson
        .{ 1.000, 0.227, 0.353, 1.0 }, // #FF3A5A - Hyper Magenta
        .{ 1.000, 0.341, 0.408, 1.0 }, // #FF5768 - Neon Coral
        .{ 1.000, 0.435, 0.235, 1.0 }, // #FF6F3C - Voltage Orange
        .{ 1.000, 0.569, 0.000, 1.0 }, // #FF9100 - Luminous Ember
        .{ 1.000, 0.835, 0.000, 1.0 }, // #FFD500 - Electric Gold
        .{ 0.843, 1.000, 0.000, 1.0 }, // #D7FF00 - Neon Citrus
        .{ 0.655, 1.000, 0.000, 1.0 }, // #A7FF00 - Radioactive Lime
        .{ 0.224, 1.000, 0.078, 1.0 }, // #39FF14 - Laser Green
        .{ 0.000, 1.000, 0.294, 1.0 }, // #00FF4B - Glowing Emerald
        .{ 0.000, 1.000, 0.659, 1.0 }, // #00FFA8 - Neon Aqua
        .{ 0.000, 0.973, 1.000, 1.0 }, // #00F8FF - Electric Cyan
        .{ 0.000, 0.749, 1.000, 1.0 }, // #00BFFF - Neon Sky
        .{ 0.000, 0.482, 1.000, 1.0 }, // #007BFF - Hyper Blue
        .{ 0.353, 0.000, 1.000, 1.0 }, // #5A00FF - Vivid Indigo
        .{ 0.651, 0.000, 1.000, 1.0 }, // #A600FF - Shockwave Violet
        .{ 0.902, 0.000, 1.000, 1.0 }, // #E600FF - Electric Amethyst
        .{ 1.000, 0.000, 0.784, 1.0 }, // #FF00C8 - Neon Orchid
        .{ 1.000, 0.000, 0.541, 1.0 }, // #FF008A - Fluorescent Fuchsia
    };

    fn fromIndex(index: usize) VibrantColor {
        const variant_count = @typeInfo(VibrantColor).@"enum".fields.len;
        return @enumFromInt(index % variant_count);
    }

    pub fn get(self: VibrantColor) [4]f32 {
        return palette[@intFromEnum(self)];
    }

    pub fn getRandom(random: std.Random) [4]f32 {
        const index = @as(u8, @intCast(std.Random.uintLessThan(random, u8, @typeInfo(VibrantColor).@"enum".fields.len)));
        return @as(VibrantColor, @enumFromInt(index)).get();
    }

    pub fn getColorByIndex(index: usize) [4]f32 {
        return fromIndex(index).get();
    }
};

// =Font===============================================================================================================

// Struct to describe the json file generated by `msdf-atlas-gen`
pub const FontAtlas = struct {
    pub const Configuration = struct {
        pub const Bounds = struct {
            left: f32,
            bottom: f32,
            right: f32,
            top: f32,
        };

        pub const Glyph = struct {
            unicode: u32,
            advance: f32,
            planeBounds: ?Bounds = null,
            atlasBounds: ?Bounds = null,
        };

        pub const Metrics = struct {
            emSize: f32,
            lineHeight: f32,
            ascender: f32,
            descender: f32,
            underlineY: f32,
            underlineThickness: f32,
        };

        pub const AtlasConfig = struct {
            type: []const u8,
            distanceRange: f32,
            distanceRangeMiddle: f32,
            size: f32,
            width: u32,
            height: u32,
            yOrigin: []const u8,
        };

        atlas: AtlasConfig,
        metrics: Metrics,
        glyphs: []Glyph,
    };

    parsed: std.json.Parsed(Configuration),

    pub fn init(allocator: std.mem.Allocator, json: []const u8) !FontAtlas {
        const parsed = try std.json.parseFromSlice(FontAtlas.Configuration, allocator, json, .{
            .ignore_unknown_fields = true,
        });
        errdefer parsed.deinit();

        return FontAtlas{
            .parsed = parsed,
        };
    }

    pub fn deinit(self: *FontAtlas) void {
        defer self.parsed.deinit();
    }

    pub fn getGlyph(self: FontAtlas, unicode: u32) ?Configuration.Glyph {
        for (self.parsed.value.glyphs) |g| {
            if (g.unicode == unicode) return g;
        }
        return null;
    }
};

// =GPUBuffers=========================================================================================================

/// Uniform buffer
pub const Uniform = extern struct {
    screen_size: [2]f32,

    /// Upper-left corner of the camera we are viewing the world with
    camera_pos: [2]f32,

    /// Zoom
    scale: f32,

    /// Padding
    _: u32 = 0,
};

/// QuadVertex buffer, a vertex that constructs a roundable quad
pub const QuadVertex = extern struct {
    pos: [3]f32,
    color: [4]f32,
    local_pos: [2]f32,
    half_size: [2]f32,
    radii: [4]f32,

    pub fn getVkBindingDiscription() [1]c.VkVertexInputBindingDescription {
        return [_]c.VkVertexInputBindingDescription{
            .{
                .binding = 0,
                .stride = @sizeOf(QuadVertex),
                .inputRate = c.VK_VERTEX_INPUT_RATE_VERTEX,
            },
        };
    }

    pub fn getVkAttributeDiscription() [5]c.VkVertexInputAttributeDescription {
        return [_]c.VkVertexInputAttributeDescription{
            .{
                .location = 0,
                .binding = 0,
                .format = c.VK_FORMAT_R32G32B32_SFLOAT,
                .offset = @offsetOf(QuadVertex, "pos"),
            },
            .{
                .location = 1,
                .binding = 0,
                .format = c.VK_FORMAT_R32G32B32A32_SFLOAT,
                .offset = @offsetOf(QuadVertex, "color"),
            },
            .{
                .location = 2,
                .binding = 0,
                .format = c.VK_FORMAT_R32G32_SFLOAT,
                .offset = @offsetOf(QuadVertex, "local_pos"),
            },
            .{
                .location = 3,
                .binding = 0,
                .format = c.VK_FORMAT_R32G32_SFLOAT,
                .offset = @offsetOf(QuadVertex, "half_size"),
            },
            .{
                .location = 4,
                .binding = 0,
                .format = c.VK_FORMAT_R32G32B32A32_SFLOAT,
                .offset = @offsetOf(QuadVertex, "radii"),
            },
        };
    }

    /// Helper function to append a quad of a solid color to a list of vertices
    /// TODO: this whole structure is super inefficient, note how we are copying color, hs and radii many times?
    fn append(
        allocator: std.mem.Allocator,
        list: *std.ArrayListUnmanaged(QuadVertex),
        x: f32,
        y: f32,
        z: f32,
        w: f32,
        h: f32,
        color: [4]f32,
        radii: [4]f32,
    ) !void {
        const hx = w / 2.0;
        const hy = h / 2.0;
        const hs = [_]f32{ hx, hy };

        try list.appendSlice(allocator, &[_]QuadVertex{
            .{
                .pos = .{ x, y, z },
                .local_pos = .{ -hx, -hy },
                .half_size = hs,
                .color = color,
                .radii = radii,
            },
            .{
                .pos = .{ x, y + h, z },
                .local_pos = .{ -hx, hy },
                .half_size = hs,
                .color = color,
                .radii = radii,
            },
            .{
                .pos = .{ x + w, y, z },
                .local_pos = .{ hx, -hy },
                .half_size = hs,
                .color = color,
                .radii = radii,
            },
            .{
                .pos = .{ x + w, y + h, z },
                .local_pos = .{ hx, hy },
                .half_size = hs,
                .color = color,
                .radii = radii,
            },
            .{
                .pos = .{ x, y + h, z },
                .local_pos = .{ -hx, hy },
                .half_size = hs,
                .color = color,
                .radii = radii,
            },
            .{
                .pos = .{ x + w, y, z },
                .local_pos = .{ hx, -hy },
                .half_size = hs,
                .color = color,
                .radii = radii,
            },
        });
    }
};

/// BezierVertex buffer
pub const BezierVertex = extern struct {
    pos: [3]f32,
    p0: [2]f32,
    p1: [2]f32,
    p2: [2]f32,
    p3: [2]f32,
    color_beg: [4]f32,
    color_end: [4]f32,
    thickness: f32,
    is_selected: f32,

    pub fn getVkBindingDiscription() [1]c.VkVertexInputBindingDescription {
        return [_]c.VkVertexInputBindingDescription{.{
            .binding = 0,
            .stride = @sizeOf(BezierVertex),
            .inputRate = c.VK_VERTEX_INPUT_RATE_VERTEX,
        }};
    }

    pub fn getVkAttributeDiscription() [9]c.VkVertexInputAttributeDescription {
        return [_]c.VkVertexInputAttributeDescription{ .{
            .location = 0,
            .binding = 0,
            .format = c.VK_FORMAT_R32G32B32_SFLOAT,
            .offset = @offsetOf(BezierVertex, "pos"),
        }, .{
            .location = 1,
            .binding = 0,
            .format = c.VK_FORMAT_R32G32_SFLOAT,
            .offset = @offsetOf(BezierVertex, "p0"),
        }, .{
            .location = 2,
            .binding = 0,
            .format = c.VK_FORMAT_R32G32_SFLOAT,
            .offset = @offsetOf(BezierVertex, "p1"),
        }, .{
            .location = 3,
            .binding = 0,
            .format = c.VK_FORMAT_R32G32_SFLOAT,
            .offset = @offsetOf(BezierVertex, "p2"),
        }, .{
            .location = 4,
            .binding = 0,
            .format = c.VK_FORMAT_R32G32_SFLOAT,
            .offset = @offsetOf(BezierVertex, "p3"),
        }, .{
            .location = 5,
            .binding = 0,
            .format = c.VK_FORMAT_R32G32B32A32_SFLOAT,
            .offset = @offsetOf(BezierVertex, "color_beg"),
        }, .{
            .location = 6,
            .binding = 0,
            .format = c.VK_FORMAT_R32G32B32A32_SFLOAT,
            .offset = @offsetOf(BezierVertex, "color_end"),
        }, .{
            .location = 7,
            .binding = 0,
            .format = c.VK_FORMAT_R32_SFLOAT,
            .offset = @offsetOf(BezierVertex, "thickness"),
        }, .{
            .location = 8,
            .binding = 0,
            .format = c.VK_FORMAT_R32_SFLOAT,
            .offset = @offsetOf(BezierVertex, "is_selected"),
        } };
    }

    pub fn append(
        allocator: std.mem.Allocator,
        list: *std.ArrayListUnmanaged(BezierVertex),
        thickness: f32,
        padding: f32,
        color_beg: [4]f32,
        color_end: [4]f32,
        is_selected: bool,
        p0: [2]f32,
        p1: [2]f32,
        p2: [2]f32,
        p3: [2]f32,
        z: f32,
    ) !void {
        const min_x = @min(p0[0], @min(p3[0], @min(p1[0], p2[0])));
        const max_x = @max(p0[0], @max(p3[0], @max(p1[0], p2[0])));
        const min_y = @min(p0[1], @min(p3[1], @min(p1[1], p2[1])));
        const max_y = @max(p0[1], @max(p3[1], @max(p1[1], p2[1])));

        const x = min_x - padding;
        const y = min_y - padding;
        const w = (max_x - min_x) + (padding * 2);
        const h = (max_y - min_y) + (padding * 2);

        try list.appendSlice(allocator, &[_]BezierVertex{
            .{
                .pos = .{ x, y, z },
                .p0 = p0,
                .p1 = p1,
                .p2 = p2,
                .p3 = p3,
                .thickness = thickness,
                .color_beg = color_beg,
                .color_end = color_end,
                .is_selected = if (is_selected) 1.0 else 0.0,
            },
            .{
                .pos = .{ x, y + h, z },
                .p0 = p0,
                .p1 = p1,
                .p2 = p2,
                .p3 = p3,
                .thickness = thickness,
                .color_beg = color_beg,
                .color_end = color_end,
                .is_selected = if (is_selected) 1.0 else 0.0,
            },
            .{
                .pos = .{ x + w, y, z },
                .p0 = p0,
                .p1 = p1,
                .p2 = p2,
                .p3 = p3,
                .thickness = thickness,
                .color_beg = color_beg,
                .color_end = color_end,
                .is_selected = if (is_selected) 1.0 else 0.0,
            },

            .{
                .pos = .{ x + w, y + h, z },
                .p0 = p0,
                .p1 = p1,
                .p2 = p2,
                .p3 = p3,
                .thickness = thickness,
                .color_beg = color_beg,
                .color_end = color_end,
                .is_selected = if (is_selected) 1.0 else 0.0,
            },
            .{
                .pos = .{ x, y + h, z },
                .p0 = p0,
                .p1 = p1,
                .p2 = p2,
                .p3 = p3,
                .thickness = thickness,
                .color_beg = color_beg,
                .color_end = color_end,
                .is_selected = if (is_selected) 1.0 else 0.0,
            },
            .{
                .pos = .{ x + w, y, z },
                .p0 = p0,
                .p1 = p1,
                .p2 = p2,
                .p3 = p3,
                .thickness = thickness,
                .color_beg = color_beg,
                .color_end = color_end,
                .is_selected = if (is_selected) 1.0 else 0.0,
            },
        });
    }
};

/// TextVertex
pub const TextVertex = extern struct {
    pos: [3]f32,
    color: [4]f32,
    uv: [2]f32,

    pub fn getVkBindingDiscription() [1]c.VkVertexInputBindingDescription {
        return [_]c.VkVertexInputBindingDescription{.{
            .binding = 0,
            .stride = @sizeOf(TextVertex),
            .inputRate = c.VK_VERTEX_INPUT_RATE_VERTEX,
        }};
    }

    pub fn getVkAttributeDiscription() [3]c.VkVertexInputAttributeDescription {
        return [_]c.VkVertexInputAttributeDescription{
            .{
                .location = 0,
                .binding = 0,
                .format = c.VK_FORMAT_R32G32B32_SFLOAT,
                .offset = @offsetOf(TextVertex, "pos"),
            },
            .{
                .location = 1,
                .binding = 0,
                .format = c.VK_FORMAT_R32G32B32A32_SFLOAT,
                .offset = @offsetOf(TextVertex, "color"),
            },
            .{
                .location = 2,
                .binding = 0,
                .format = c.VK_FORMAT_R32G32_SFLOAT,
                .offset = @offsetOf(TextVertex, "uv"),
            },
        };
    }

    // TODO: vibed I don't get this part
    pub fn append(
        allocator: std.mem.Allocator,
        atlas: FontAtlas,
        text: []const u8,
        align_mode: enum { Left, Center, Right },
        x: f32,
        y: f32,
        z: f32,
        max_w: f32,
        font_size: f32,
        list: *std.ArrayList(TextVertex),
    ) !void {
        const scale = font_size / atlas.parsed.value.metrics.emSize;
        const atlas_w = @as(f32, @floatFromInt(atlas.parsed.value.atlas.width));
        const atlas_h = @as(f32, @floatFromInt(atlas.parsed.value.atlas.height));

        var current_width: f32 = 0.0;
        var dot_width: f32 = 0.0;
        if (atlas.getGlyph('.')) |g| dot_width = g.advance * scale;

        var draw_len: usize = text.len;
        var needs_dots = false;
        var measured_w: f32 = 0.0;

        for (text) |char| {
            const g = atlas.getGlyph(char) orelse continue;
            const adv = g.advance * scale;
            if (current_width + adv > max_w) {
                needs_dots = true;
                break;
            }
            current_width += adv;
            measured_w = current_width;
        }

        if (needs_dots) {
            current_width = 0.0;
            const target_w = max_w - (dot_width * 3.0);
            draw_len = 0;
            if (target_w > 0) {
                for (text) |char| {
                    const g = atlas.getGlyph(char) orelse continue;
                    const adv = g.advance * scale;
                    if (current_width + adv > target_w) break;
                    current_width += adv;
                    draw_len += 1;
                }
            }
            measured_w = current_width + (dot_width * 3.0);
        }

        var cursor_x: f32 = switch (align_mode) {
            .Left => x,
            .Center => x - (measured_w / 2.0),
            .Right => x - measured_w,
        };
        const cursor_y = y;
        const text_color = [_]f32{ 1.0, 1.0, 1.0, 1.0 };

        const dots_to_draw: usize = if (needs_dots) 3 else 0;
        var i: usize = 0;

        while (i < draw_len + dots_to_draw) : (i += 1) {
            const char = if (i < draw_len) text[i] else '.';
            const glyph = atlas.getGlyph(char) orelse continue;

            if (glyph.planeBounds) |pb| {
                if (glyph.atlasBounds) |ab| {
                    const screen_l = cursor_x + (pb.left * scale);
                    const screen_r = cursor_x + (pb.right * scale);
                    const screen_t = cursor_y - (pb.top * scale);
                    const screen_b = cursor_y - (pb.bottom * scale);

                    const uv_l = ab.left / atlas_w;
                    const uv_r = ab.right / atlas_w;
                    const uv_t = (atlas_h - ab.top) / atlas_h;
                    const uv_b = (atlas_h - ab.bottom) / atlas_h;

                    const quads = [_]TextVertex{
                        .{ .pos = .{ screen_l, screen_t, z }, .uv = .{ uv_l, uv_t }, .color = text_color },
                        .{ .pos = .{ screen_l, screen_b, z }, .uv = .{ uv_l, uv_b }, .color = text_color },
                        .{ .pos = .{ screen_r, screen_t, z }, .uv = .{ uv_r, uv_t }, .color = text_color },
                        .{ .pos = .{ screen_r, screen_b, z }, .uv = .{ uv_r, uv_b }, .color = text_color },
                        .{ .pos = .{ screen_l, screen_b, z }, .uv = .{ uv_l, uv_b }, .color = text_color },
                        .{ .pos = .{ screen_r, screen_t, z }, .uv = .{ uv_r, uv_t }, .color = text_color },
                    };
                    try list.appendSlice(allocator, &quads);
                }
            }
            cursor_x += glyph.advance * scale;
        }
    }
};

// =Pipewire===========================================================================================================

pub const PipewireLink = struct {
    node_id: u32,
    port_id: u32,
    link_id: u32,
    is_selected: bool = false,
};

pub const PipewirePort = struct {
    name: []const u8,
    connections: std.AutoArrayHashMapUnmanaged(u32, PipewireLink) = .empty,

    pub fn deinit(self: *PipewirePort, allocator: std.mem.Allocator) void {
        allocator.free(self.name);
        self.connections.deinit(allocator);
    }
};

/// Height spacing between nodes
pub const H_NODE_SPACING: f32 = 100.0;

/// Width spacing between nodes
pub const W_NODE_SPACING: f32 = 300.0;

pub const PipewireNode = struct {
    /// Standard color of the node
    pub const NODE_COLOR: [4]f32 = .{ 0.2, 0.2, 0.2, 1.0 };

    /// Fixed width of the node
    pub const W_NODE: f32 = 400.0;

    /// Height reserved for the the title of the node
    pub const H_OFFSET_TITLE: f32 = 50.0;

    /// Width reserved for the the title of the node
    pub const W_OFFSET_TITLE: f32 = 0.0;

    // Distance from left or right edge for a given pin
    pub const W_OFFSET_OUTER_PIN: f32 = 0.0;

    /// Height reserved per pin
    pub const H_OFFSET_OUTER_PIN: f32 = 50.0;

    /// Width internal offset before drawing the pin
    pub const W_OFFSET_INNER_PIN: f32 = 0.0;

    /// Height internal offset before drawing the pin
    pub const H_OFFSET_INNER_PIN: f32 = 12.5;

    /// Height of pin
    pub const H_PIN: f32 = 25;

    /// Width of pin
    pub const W_PIN: f32 = 12.5;

    node_id: u32,
    name: []const u8,
    inps: std.AutoArrayHashMapUnmanaged(u32, PipewirePort) = .empty,
    outs: std.AutoArrayHashMapUnmanaged(u32, PipewirePort) = .empty,

    // for drawing, honestly probably shouldnt live here but I'll allow it
    x: ?f32 = null,
    y: ?f32 = null,
    z: ?f32 = null,
    port_color: ?[4]f32 = null,

    /// Computes the maximum number of pins for displaying the node, i.e. max(inp_count, out_count).
    fn computePortSlotCount(self: PipewireNode) usize {
        return @max(self.inps.count(), self.outs.count());
    }

    /// Computes the total height of the given node
    pub fn computeNodeHeight(self: PipewireNode) f32 {
        return H_OFFSET_TITLE + (H_OFFSET_OUTER_PIN * @as(f32, @floatFromInt(self.computePortSlotCount())));
    }

    fn computePortColor(self: PipewireNode, index: usize) [4]f32 {
        const base = self.port_color.?;
        const burn = 1.0 - 0.8 * @as(f32, @floatFromInt(index)) / @as(f32, @floatFromInt(self.computePortSlotCount()));
        return .{ burn * base[0], burn * base[1], burn * base[2], base[3] };
    }
    /// Grab the x-coordinate of the given input pin
    fn getInpPortX(self: PipewireNode, _: usize) f32 {
        return self.x.?;
    }

    /// Grab the x-coordinate of the given output pin
    pub fn getOutPortX(self: PipewireNode, _: usize) f32 {
        return self.x.? + W_NODE;
    }

    /// Grab the y-coordinate of the given input pin
    pub fn getInpPortY(self: PipewireNode, index: usize) f32 {
        const findex = @as(f32, @floatFromInt(index));
        return self.y.? + H_OFFSET_TITLE + (findex * H_OFFSET_OUTER_PIN) + H_OFFSET_INNER_PIN + H_PIN / 2;
    }

    /// Grab the y-coordinate of the given output pin
    pub fn getOutPortY(self: PipewireNode, index: usize) f32 {
        const findex = @as(f32, @floatFromInt(index));
        return self.y.? + H_OFFSET_TITLE + (findex * H_OFFSET_OUTER_PIN) + H_OFFSET_INNER_PIN + H_PIN / 2;
    }

    /// Appends the QuadVertexs required to draw the current node to an existing list of vertives
    pub fn appendVerticesNode(
        self: PipewireNode,
        allocator: std.mem.Allocator,
        list: *std.ArrayListUnmanaged(QuadVertex),
    ) !void {
        const H_NODE = self.computeNodeHeight();
        const color: [4]f32 = .{ 0.2, 0.2, 0.2, 1.0 };
        const radii: [4]f32 = .{ 10.0, 10.0, 10.0, 10.0 };
        try QuadVertex.append(allocator, list, self.x.?, self.y.?, self.z.? + 0.3, W_NODE, H_NODE, color, radii);
    }

    /// Appends the QuadVertexs required to draw the pins of the current node to an existing list of vertives
    pub fn appendVerticesPorts(
        self: PipewireNode,
        allocator: std.mem.Allocator,
        list: *std.ArrayListUnmanaged(QuadVertex),
    ) !void {
        // LHS of the node
        {
            const H_BEG: f32 = H_OFFSET_TITLE;
            const W_BEG: f32 = 0;
            const radii = .{ 2.5, 2.5, 0.0, 0.0 };
            for (0..self.inps.count()) |i| {
                const px = self.x.? + W_BEG + @as(f32, @floatFromInt(i)) * W_OFFSET_OUTER_PIN + W_OFFSET_INNER_PIN;
                const py = self.y.? + H_BEG + @as(f32, @floatFromInt(i)) * H_OFFSET_OUTER_PIN + H_OFFSET_INNER_PIN;
                try QuadVertex.append(allocator, list, px, py, self.z.? + 0.1, W_PIN, H_PIN, self.computePortColor(i), radii);
            }
        }

        // RHS of the node
        {
            const H_BEG: f32 = H_OFFSET_TITLE;
            const W_BEG: f32 = W_NODE - W_OFFSET_INNER_PIN * 2 - W_PIN;
            const radii = .{ 0.0, 0.0, 2.5, 2.5 };
            for (0..self.outs.count()) |i| {
                const px = self.x.? + W_BEG + @as(f32, @floatFromInt(i)) * W_OFFSET_OUTER_PIN + W_OFFSET_INNER_PIN;
                const py = self.y.? + H_BEG + @as(f32, @floatFromInt(i)) * H_OFFSET_OUTER_PIN + H_OFFSET_INNER_PIN;
                try QuadVertex.append(allocator, list, px, py, self.z.? + 0.1, W_PIN, H_PIN, self.computePortColor(i), radii);
            }
        }
    }

    fn getBezierPoint(
        t: f32,
        p0: [2]f32,
        p1: [2]f32,
        p2: [2]f32,
        p3: [2]f32,
    ) [2]f32 {
        const inv_t: f32 = 1.0 - t;
        return [_]f32{
            inv_t * inv_t * inv_t * p0[0] +
                3.0 * inv_t * inv_t * t * p1[0] +
                3.0 * inv_t * t * t * p2[0] +
                t * t * t * p3[0],
            inv_t * inv_t * inv_t * p0[1] +
                3.0 * inv_t * inv_t * t * p1[1] +
                3.0 * inv_t * t * t * p2[1] +
                t * t * t * p3[1],
        };
    }

    fn getBezierDeriv(
        t: f32,
        p0: [2]f32,
        p1: [2]f32,
        p2: [2]f32,
        p3: [2]f32,
    ) [2]f32 {
        const inv_t: f32 = 1.0 - t;
        return [_]f32{
            3.0 * inv_t * inv_t * (p1[0] - p0[0]) +
                6.0 * inv_t * t * (p2[0] - p1[0]) +
                3.0 * t * t * (p3[0] - p2[0]),
            3.0 * inv_t * inv_t * (p1[1] - p0[1]) +
                6.0 * inv_t * t * (p2[1] - p1[1]) +
                3.0 * t * t * (p3[1] - p2[1]),
        };
    }

    pub fn markNearbyLinks(
        self: PipewireNode,
        other_nodes: std.AutoArrayHashMapUnmanaged(u32, PipewireNode),
        pos: [2]f32,
    ) !void {
        var self_node_index: usize = 0;
        var it = self.outs.iterator();
        while (it.next()) |out_entry| : (self_node_index += 1) {
            const out_port = out_entry.value_ptr.*;
            var link_it = out_port.connections.iterator();

            while (link_it.next()) |*link_entry| {
                const link = link_entry.value_ptr.*;
                const other = other_nodes.get(link.node_id) orelse continue;
                const other_node_index = other.getInpPortVisualIndex(link.port_id) orelse return error.PipewireError;
                const bbox = self.computeBezierBoundingBox(self_node_index, other, other_node_index);

                // Get closest point on curve
                var t: f32 = 0.5;
                for (0..4) |_| {
                    const point = getBezierPoint(t, bbox.p0, bbox.p1, bbox.p2, bbox.p3);
                    const deriv = getBezierDeriv(t, bbox.p0, bbox.p1, bbox.p2, bbox.p3);
                    const diff = [_]f32{ point[0] - pos[0], point[1] - pos[1] };
                    t = t - (diff[0] * deriv[0] + diff[1] * deriv[1]) / (deriv[0] * deriv[0] + deriv[1] * deriv[1]);
                    t = @min(@max(t, 0.0), 1.0);
                }

                const point = getBezierPoint(t, bbox.p0, bbox.p1, bbox.p2, bbox.p3);
                const dist = @sqrt(
                    (point[0] - pos[0]) * (point[0] - pos[0]) + (point[1] - pos[1]) * (point[1] - pos[1]),
                );

                if (dist < 10.0) {
                    link_entry.value_ptr.is_selected = true;
                } 
            }
        }
    }

    pub fn getInpPortVisualIndex(self: PipewireNode, port_id: u32) ?usize {
        var it = self.inps.iterator();
        var i: usize = 0;
        while (it.next()) |entry| : (i += 1) {
            if (entry.key_ptr.* == port_id) return i;
        }

        return null;
    }

    fn computeBezierBoundingBox(
        self: PipewireNode,
        self_node_index: usize,
        other: PipewireNode,
        other_node_index: usize,
    ) struct {
        p0: [2]f32,
        p1: [2]f32,
        p2: [2]f32,
        p3: [2]f32,
    } {
        const p0 = [2]f32{
            self.x.? + W_NODE,
            self.y.? + H_OFFSET_TITLE + (@as(f32, @floatFromInt(self_node_index)) * H_OFFSET_OUTER_PIN) + //
                H_OFFSET_INNER_PIN + (H_PIN / 2.0),
        };

        const p3 = [2]f32{
            other.x.?,
            other.y.? + H_OFFSET_TITLE + (@as(f32, @floatFromInt(other_node_index)) * H_OFFSET_OUTER_PIN) + //
                H_OFFSET_INNER_PIN + (H_PIN / 2.0),
        };

        const offset = @abs(p3[0] - p0[0]) / 2.0;

        const p1 = [2]f32{
            p0[0] + offset,
            p0[1],
        };

        const p2 = [2]f32{
            p3[0] - offset,
            p3[1],
        };

        return .{
            .p0 = p0,
            .p1 = p1,
            .p2 = p2,
            .p3 = p3,
        };
    }

    /// Appends the BezierVertexs required to draw the links of the current node
    pub fn appendVerticesLinks(
        self: PipewireNode,
        allocator: std.mem.Allocator,
        other_nodes: std.AutoArrayHashMapUnmanaged(u32, PipewireNode),
        list: *std.ArrayListUnmanaged(BezierVertex),
    ) !void {

        // NOTE: funny thing about our architecture, we have both input and output connections! But we only draw
        // outputs, to not draw twice...
        var self_node_index: usize = 0;
        var it = self.outs.iterator();
        while (it.next()) |out_entry| : (self_node_index += 1) {
            const out_port = out_entry.value_ptr.*;
            var link_it = out_port.connections.iterator();

            while (link_it.next()) |link_entry| {
                const link = link_entry.value_ptr.*;

                // Find where this input port actually sits visually
                const other = other_nodes.get(link.node_id) orelse continue;
                const other_node_index = other.getInpPortVisualIndex(link.port_id) orelse return error.PipewireError;

                // Compute exact centers of the output and input pins
                const bbox = self.computeBezierBoundingBox(self_node_index, other, other_node_index);

                try BezierVertex.append(
                    allocator,
                    list,
                    4.0,
                    10.0,
                    self.computePortColor(self_node_index),
                    other.computePortColor(other_node_index),
                    link_entry.value_ptr.is_selected,
                    bbox.p0,
                    bbox.p1,
                    bbox.p2,
                    bbox.p3,
                    self.z.? + 0.2,
                );
            }
        }
    }

    pub fn appendVerticesText(
        self: PipewireNode,
        allocator: std.mem.Allocator,
        atlas: FontAtlas,
        list: *std.ArrayListUnmanaged(TextVertex),
    ) !void {
        const title_max_w = W_NODE - 20.0;
        const title_x = self.x.? + (W_NODE / 2.0);
        const title_y = self.y.? + 30.0;

        try TextVertex.append(
            allocator,
            atlas,
            self.name,
            .Center,
            title_x,
            title_y,
            self.z.? + 0.2,
            title_max_w,
            16.0,
            list,
        );

        {
            var i: usize = 0;
            var port_it = self.inps.iterator();
            while (port_it.next()) |port| : (i += 1) {
                const port_x = self.x.? + W_OFFSET_INNER_PIN + W_PIN + 8.0;
                const port_y = self.getInpPortY(i) + 4.0;
                const port_max_w = (W_NODE / 2.0) - W_PIN - 12.0;

                try TextVertex.append(
                    allocator,
                    atlas,
                    port.value_ptr.name,
                    .Left,
                    port_x,
                    port_y,
                    self.z.?,
                    port_max_w,
                    12.0,
                    list,
                );
            }
        }

        {
            var i: usize = 0;
            var port_it = self.outs.iterator();
            while (port_it.next()) |port| : (i += 1) {
                const port_x = self.x.? + W_NODE - W_OFFSET_INNER_PIN - W_PIN - 8.0;
                const port_y = self.getInpPortY(i) + 4.0;
                const port_max_w = (W_NODE / 2.0) - W_PIN - 12.0;

                try TextVertex.append(
                    allocator,
                    atlas,
                    port.value_ptr.name,
                    .Right,
                    port_x,
                    port_y,
                    self.z.?,
                    port_max_w,
                    12.0,
                    list,
                );
            }
        }
    }

    pub fn deinit(self: *PipewireNode, allocator: std.mem.Allocator) void {
        allocator.free(self.name);

        {
            var port_it = self.inps.iterator();
            while (port_it.next()) |*port| {
                port.value_ptr.deinit(allocator);
            }
        }

        self.inps.deinit(allocator);

        {
            var port_it = self.outs.iterator();
            while (port_it.next()) |*port| {
                port.value_ptr.deinit(allocator);
            }
        }

        self.outs.deinit(allocator);
    }
};

//
